export const coffeeTicketData = {
    'coffeeTicketList': [{ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
        {ticketLevel: 'A', ticketPrice: 30, ticketType: '摩卡', remainCups: 2},
        {ticketLevel: 'B', ticketPrice: 25, ticketType: '卡布其诺', remainCups: 12},
        {ticketLevel: 'C', ticketPrice: 20, ticketType: '焦糖', remainCups: 3},
    ],

}

